exports.domain = 'http://localhost:3000';
exports.res =
    [{
        route: '/',
        method: 'GET',
        view: 'pages/saunter',
        url: '/stub/',
        params: []
    }, {
        route: '/optimize',
        method: 'GET',
        view: 'pages/saunter-optimize',
        url: '/stub/optimize',
        params: []
    }, {
        route: '/tag',
        method: 'GET',
        view: 'pages/tag',
        url: '/stub/tag',
        params: []
    }, {
        route: '/editor',
        method: 'GET',
        view: 'pages/tag',
        url: '/stub/editor',
        params: []
    }, {
        route: '/ps',
        method: 'GET',
        view: 'pages/ps',
        url: '/stub/ps',
        params: []
    }, {
        route: '/tpl',
        method: 'GET',
        view: 'pages/template',
        url: '/stub/tpl',
        params: []
    }, {
        route: '/err',
        method: 'GET',
        view: 'error/error',
        url: '/stub/err',
        params: []
    }];